### ISSUE TITLE
Change references to PyGSP to PyGSP2 when installing with pip

### ISSUE THREAD

**Issue by aweinstein** [gsp-eeg/pygsp2#34]
When we install PyGSP2 with pip, there are references to `PyGSP`:
```
$ pip install -e .
Obtaining file:///home/ajw/Dropbox/ibm/proyectos/fondecyt/code/pygsp2
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /home/ajw/.virtualenvs/eegrasp/lib/python3.12/site-packages (from PyGSP==0.5.1) (2.0.0)
Requirement already satisfied: scipy in /home/ajw/.virtualenvs/eegrasp/lib/python3.12/site-packages (from PyGSP==0.5.1) (1.14.0)
Building wheels for collected packages: PyGSP
  Building editable for PyGSP (pyproject.toml) ... done
  Created wheel for PyGSP: filename=PyGSP-0.5.1-0.editable-py3-none-any.whl size=6582 sha256=caae693008859fe14ccd8e82a9707b5a809ffaa82435d00cece5cd9fa28e2658
  Stored in directory: /tmp/pip-ephem-wheel-cache-ri71bvz8/wheels/bb/3b/50/33d2d82c66ce4362bd588d286464888a9063a00d2d8f2f2715
Successfully built PyGSP
Installing collected packages: PyGSP
Successfully installed PyGSP-0.5.1
```

Change these references to PyGSP2. Also, note that the installation points to version 0.5.1 of PyGSP (at least is what this message says). I'm not sure if we need to change something else to install the latest PyGSP2 version (the one in the master branch).

**Comment by lcortesg** [comment]
Which branch is presenting this problem? could you try a `pip install pygsp2`?

**Comment by aweinstein** [comment]
The problem is with the master branch.  I guess we haven't pushed the name changes into master. 

`pip install pygsp2` into a new virtualenv does not mention PyGSP.

**Comment by cjotade** [comment]
The command "pip install -e ." is used in the context of Python package installation, specifically for development installations.
    -e: This stands for --editable, indicating that the package should be installed in editable mode.
    .: This refers to the current directory. It indicates that the package to be installed is located in the current directory.

When you use pip install -e ., you are telling pip to install the package located in the current directory in editable mode.

As we haven't had the merge request #25, the dependencies are not updated with PyGSP2.

By using "pip install pygsp2" as @lcortesg mentioned the installation should be correct since the wheels of Pypi are updated using the [22-change-basename-folder-to-pygsp2](https://github.com/gsp-eeg/pygsp2/tree/22-change-basename-folder-to-pygsp2) branch
